### ISSUE TITLE
Note For Thesis

### ISSUE THREAD

**Issue by dedeklmta** [imamdigmi/simple-recruitment-dss-ahp#1]
1. jikalau data dihapus semua, terus inputin lagi maka akan terjadi erorr
2. Pencarian tentang table
3. validasi data penginputan
4. Nilai diganti dengan Skala dasar AHP, hanya redaksi di web
5. Ketua hanya mellihat laporan 
6. penjelasan hasil perbandingan
7. Data rangking langsung ke ranking saja
8. arti dari diagonal angka "1"
9. tentang perhitungan, Rumus belum selesai, yang dibagian rangking 
   disitu rangking belum urut 
10. Data Kriteria dan Data alternatif Harus bisa > 5 dan harus bisa < 5

**Comment by imamdigmi** [comment]
sudah di pecah menjadi beberapa issue agar fix lebih mudah di track dari tiap-tiap error
