### ISSUE TITLE
Ranking

### ISSUE THREAD

**Issue by imamdigmi** [imamdigmi/simple-recruitment-dss-ahp#10]
Data rangking langsung ke ranking saja

**Comment by dedeklmta** [comment]
Data rangking pas di laporan itu mam, kan redaksinya data ranking, trs yg keluar disitu harus sudah terurut rankingnya, kmren kan belum

**Comment by imamdigmi** [comment]
Ooooh, brarti cuman pengurutan yaah?

**Comment by imamdigmi** [comment]
Redaksinya harusnya gimana dek?

**Comment by dedeklmta** [comment]
Redaksinya kan disitu Data ranking, nah trs yang dikeluarin data ranking yg udh di urut sesuai rumus aja, data2 yg diiputin ndk usah ditampilin lagi mam

**Comment by dedeklmta** [comment]
Langsung tampilkan ranking dihalaman ranking
