### ISSUE TITLE
database problem

### ISSUE THREAD

**Issue by dedeklmta** [imamdigmi/simple-recruitment-dss-ahp#15]
mam, database nya yang:
 nilai
 nilai_awal
 nilai_awal_detail
itu udah ndak berguna kan yak? brrti dihapus aja mam kalo emang ndk ada relasinya, thanksss

**Comment by dedeklmta** [comment]
oiya, sama databasenya "skala dasar AHP" belum ada, yang seharusnya fielnya itu adalah:
1. id_nilai
2. jum_nilai
3. ket nilai
nah itu yang di inputin wakil itu loh, dia kan berelasi sama table data_kriteria yang udah kamu bikin, gitu dulu deh, sorry banyak issue mam, but take over more important

**Comment by imamdigmi** [comment]
udah ada de, nama tabel nya **nilai**
