### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by dedeklmta** [imamdigmi/simple-recruitment-dss-ahp#2]
1. Tanggal lahir automatic, jadi harus keluar tanggal/kalender.
2. Penilaian sama kriteria nya masih blm mudeng, dipage penilaian.
3. Menentukan bobot sama untuk menilai calon anggota yang masih bingung.

**Comment by imamdigmi** [comment]
Halo @dedeklmta.

1. Tanggal lahir dibuat otomatis karena dalam hal penyimpanan data, format yang seragam akan lebih baik dan memudahkan kita dalam pencarian dan sebagainya.
2. Pada saat penilaian, user hanya perlu memilih NIM (calon anggota), kriteria, dan nilai untuk masing-masing kriteria tersebut.
3. Pada saat perhitungan (implementasi metode AHP) pada penilaian nanti, user hanya perlu menentukan kriteria bukan bobotnya, dan tentunya nilai bobot pada kriteria tersebut bisa langsung menyesuaikan pada saat user memilih kriteria, alasannya adalah untuk memudahkan si user.

**Comment by dedeklmta** [comment]
Ok mam, nanti tak pahami lagi ya, so, tunggu kabar selanjutnya ya mam

**Comment by dedeklmta** [comment]
Oiya mam, untuk logo sama foto yang mau akan di tampilkan di Home.php aku kirimnya lewat mana ya? apa lewat e-mail aja lebih enak?

**Comment by imamdigmi** [comment]
Oke, cek juga commit yg terbaru [disini](https://github.com/imamdigmi/simple-recruitment-dss-ahp/commit/e410bb1cf06c09eb3e6a9fa0768cad35de7eeba7), dan issue ini aku close yaah.

**Comment by imamdigmi** [comment]
boleh kirim di email aja.

**Comment by dedeklmta** [comment]
1. Di hasil inputan sistem harus bisa mencari calon anggota, sistem pencarian berdasarkan NIM, JURUSAN, NAMA
2. Jenis alamat diganti, bukan text tapi textarea biar bisa inputkan banyak huruf yg ada di kotak dialog alamat
3. Tambahkan validasi inputan setiap form2 yanh di inputkan user. Ex: ketika kita mau masukkan NIM, tp user salah inputkan, yg di inputkan seharusnya angka, ttpi user malah inputkan huruf, jd sistem harus diberi validasi inputan sehingga tidak ada kebingungan pada user yg menggunakan sistem itu tersebut

Thanks

**Comment by imamdigmi** [comment]
bikin issue baru aja de, biar nnti klo udh slesai aku asign ke issue terkait.
