### ISSUE TITLE
nomor pada ranking

### ISSUE THREAD

**Issue by dedeklmta** [imamdigmi/simple-recruitment-dss-ahp#25]
mam, yang di ranking itu dikasih nomor ya mam, biar enak liatnya, thanks

**Comment by dedeklmta** [comment]
mam, sini kos, binung aku mau hubungi km pke apaa

**Comment by rizqyananta** [comment]
kok tidak bisa upload database ya

**Comment by imamdigmi** [comment]
gak bisa upload nya gimana yaah? @rizqyananta

**Comment by dedeklmta** [comment]
ss aja errornya gimana?
